rule Detect_PowerShell_EncodedCommand
{
    meta:
        description = "Detects PowerShell EncodedCommand in EXE files generated by Python code"
        author = "ChatGPT"
        date = "2025-03-25"

    strings:
        $powershell_encoded_command = "powershell -EncodedCommand"

    condition:
        $powershell_encoded_command
}
